# Generated by Django 4.0.4 on 2022-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201205_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('refund', models.IntegerField()),
                ('show_name', models.CharField(max_length=20)),
                ('tier', models.CharField(max_length=10)),
                ('event_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
