# Generated by Django 4.0.4 on 2022-07-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stadiums'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stadiums',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
